### ISSUE TITLE
Suggest Not Including data context discussion in "understanding-dataloader.md"

### ISSUE THREAD

**Issue by pkellner** [ChilliCream/graphql-workshop#25]
I would suggest not teaching people to setup the project incorrectly but go directly to setting up correctly with attribute that supports the middleware.  Maybe in passing mention the wrong way to set it up but no need to go through all the details. Most people will just follow what you suggest.

That is, explain the setup in the first chapter, then have the dataloader discussion just be about dataloader.

**Comment by gojanpaolo** [comment]
@michaelstaib I also think there are parts that discusses EF / db that we could remove and/or move to have more focus on graphql and HC.
What do you think of these action items?

- [ ] Write up a session 0 explaining the the data classes, db setup, some ef stuff, etc
- [ ] Automatically create database on `Startup` (this should also resolve https://github.com/ChilliCream/graphql-workshop/issues/38)
- [ ] Ensure all sample code work (especially mutation) because it may fail a constraint with the full sql schema
- [ ] Remove db Migrations
- [ ] Remove ["Configuring EF Migrations"](https://github.com/ChilliCream/graphql-workshop/blob/master/docs/1-creating-a-graphql-server-project.md#configuring-ef-migrations)
- [ ] Seed database with test data (see https://github.com/ChilliCream/graphql-workshop/issues/15#issuecomment-761726972)
- [ ] Remove ["Adding the remaining data models"](https://github.com/ChilliCream/graphql-workshop/blob/master/docs/3-understanding-dataLoader.md#adding-the-remaining-data-models)
- [ ] Go straight to using `IDbContextFactory` and `UseApplicationDbContext`

**Comment by glen-84** [comment]
I'm closing this issue as outdated, as we have an updated workshop on the `main` branch, for Hot Chocolate 14.
